# Generated by scripts/generate_cli_artifacts.py; do not edit.
_jring_completion()
{
    local current command previous words index word option_prefix option_value
    current="${COMP_WORDS[COMP_CWORD]}"
    previous=""
    if (( COMP_CWORD > 0 )); then previous="${COMP_WORDS[COMP_CWORD-1]}"; fi
    command=""

    for (( index=1; index < COMP_CWORD; index++ )); do
        word="${COMP_WORDS[index]}"
        case "$word" in
            --address|--address-file|--simulate-profile|--timeout) ((index++)) ;;
            doctor|input-actions|protocol-coverage|non-health-capabilities|input|discover|status|capabilities|time-sync|history) command="$word"; break ;;
        esac
    done

    if [[ -z "$command" ]]; then
        case "$current" in
            --address-file=*)
                option_prefix="${current%%=*}="
                option_value="${current#*=}"
                compopt -o filenames 2>/dev/null || true
                mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
                for index in "${!COMPREPLY[@]}"; do
                    COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
                done
                return
                ;;
            --simulate-profile=*)
                option_prefix="${current%%=*}="
                option_value="${current#*=}"
                mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$option_value")
                for index in "${!COMPREPLY[@]}"; do
                    COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
                done
                return
                ;;
            --address=*|--timeout=*)
                COMPREPLY=()
                return
                ;;
        esac
        case "$previous" in
            --address-file)
                compopt -o filenames 2>/dev/null || true
                mapfile -t COMPREPLY < <(compgen -f -- "$current")
                return
                ;;
            --simulate-profile)
                mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$current")
                return
                ;;
            --address|--timeout)
                COMPREPLY=()
                return
                ;;
        esac
        words='-h --help --version --address --address-file --simulate --simulate-profile --timeout --json doctor input-actions protocol-coverage non-health-capabilities input discover status capabilities time-sync history'
        mapfile -t COMPREPLY < <(compgen -W "$words" -- "$current")
        return
    fi

    case "$command" in
        doctor) words='-h --help --json --require-hardware --require-input' ;;
        input-actions) words='-h --help --json' ;;
        protocol-coverage) words='-h --help --json' ;;
        non-health-capabilities) words='-h --help --json' ;;
        input) words='-h --help --simulate --simulate-profile --json --map --allow-input' ;;
        discover) words='-h --help --simulate --timeout --json --active-scan' ;;
        status) words='-h --help --address --address-file --simulate --simulate-profile --timeout --json --select --active-scan' ;;
        capabilities) words='-h --help --address --address-file --simulate --simulate-profile --timeout --json --select --active-scan' ;;
        time-sync) words='-h --help --address --address-file --simulate --timeout --json --allow-write --yes' ;;
        history) words='-h --help --simulate --json --output --force' ;;
        *) return ;;
    esac

    case "$command:$current" in
        input:--simulate-profile=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        input:--map=*)
            COMPREPLY=()
            return
            ;;
        discover:--timeout=*)
            COMPREPLY=()
            return
            ;;
        status:--address-file=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        status:--simulate-profile=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        status:--address=*|status:--timeout=*)
            COMPREPLY=()
            return
            ;;
        capabilities:--address-file=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        capabilities:--simulate-profile=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        capabilities:--address=*|capabilities:--timeout=*)
            COMPREPLY=()
            return
            ;;
        time-sync:--address-file=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        time-sync:--address=*|time-sync:--timeout=*)
            COMPREPLY=()
            return
            ;;
        history:--output=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
    esac

    case "$command:$previous" in
        input:--simulate-profile)
            mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$current")
            return
            ;;
        input:--map)
            COMPREPLY=()
            return
            ;;
        discover:--timeout)
            COMPREPLY=()
            return
            ;;
        status:--address-file)
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$current")
            return
            ;;
        status:--simulate-profile)
            mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$current")
            return
            ;;
        status:--address|status:--timeout)
            COMPREPLY=()
            return
            ;;
        capabilities:--address-file)
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$current")
            return
            ;;
        capabilities:--simulate-profile)
            mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$current")
            return
            ;;
        capabilities:--address|capabilities:--timeout)
            COMPREPLY=()
            return
            ;;
        time-sync:--address-file)
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$current")
            return
            ;;
        time-sync:--address|time-sync:--timeout)
            COMPREPLY=()
            return
            ;;
        history:--output)
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$current")
            return
            ;;
    esac
    mapfile -t COMPREPLY < <(compgen -W "$words" -- "$current")
}
complete -F _jring_completion jring
