# Generated by scripts/generate_cli_artifacts.py; do not edit.
_jring_completion()
{
    local current command previous words index word option_prefix option_value
    current="${COMP_WORDS[COMP_CWORD]}"
    previous=""
    if (( COMP_CWORD > 0 )); then previous="${COMP_WORDS[COMP_CWORD-1]}"; fi
    command=""

    for (( index=1; index < COMP_CWORD; index++ )); do
        word="${COMP_WORDS[index]}"
        case "$word" in
            --address|--address-file|--simulate-profile|--timeout) ((index++)) ;;
            doctor|input-actions|tui|completion|protocol-coverage|non-health-capabilities|input|discover|pair|status|capabilities|heart-rate|time-sync|history|verify-device-info|observe|review-observation|review-owner-evidence|derive-owner-evidence) command="$word"; break ;;
        esac
    done

    if [[ -z "$command" ]]; then
        case "$current" in
            --address-file=*)
                option_prefix="${current%%=*}="
                option_value="${current#*=}"
                compopt -o filenames 2>/dev/null || true
                mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
                for index in "${!COMPREPLY[@]}"; do
                    COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
                done
                return
                ;;
            --simulate-profile=*)
                option_prefix="${current%%=*}="
                option_value="${current#*=}"
                mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$option_value")
                for index in "${!COMPREPLY[@]}"; do
                    COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
                done
                return
                ;;
            --address=*|--timeout=*)
                COMPREPLY=()
                return
                ;;
        esac
        case "$previous" in
            --address-file)
                compopt -o filenames 2>/dev/null || true
                mapfile -t COMPREPLY < <(compgen -f -- "$current")
                return
                ;;
            --simulate-profile)
                mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$current")
                return
                ;;
            --address|--timeout)
                COMPREPLY=()
                return
                ;;
        esac
        words='-h --help --version --address --address-file --simulate --simulate-profile --timeout --json doctor input-actions tui completion protocol-coverage non-health-capabilities input discover pair status capabilities heart-rate time-sync history verify-device-info observe review-observation review-owner-evidence derive-owner-evidence'
        mapfile -t COMPREPLY < <(compgen -W "$words" -- "$current")
        return
    fi

    case "$command" in
        doctor) words='-h --help --json --require-hardware --require-input' ;;
        input-actions) words='-h --help --json' ;;
        tui) words='-h --help' ;;
        completion) words='-h --help' ;;
        protocol-coverage) words='-h --help --json' ;;
        non-health-capabilities) words='-h --help --json' ;;
        input) words='-h --help --simulate --simulate-profile --json --map --allow-input' ;;
        discover) words='-h --help --simulate --timeout --json --active-scan' ;;
        pair) words='-h --help --address-file --allow-pairing --allow-trust --timeout --json' ;;
        status) words='-h --help --address --address-file --simulate --simulate-profile --timeout --json --select --active-scan' ;;
        capabilities) words='-h --help --address --address-file --simulate --simulate-profile --timeout --json --select --active-scan --issue-draft-url --include-observation-targets' ;;
        heart-rate) words='-h --help --address --address-file --simulate --simulate-profile --timeout --json --select --active-scan --allow-notifications' ;;
        time-sync) words='-h --help --address --address-file --simulate --timeout --json --allow-write --yes' ;;
        history) words='-h --help --simulate --json --output --force' ;;
        verify-device-info) words='-h --help --address-file --private-output --model-family --firmware-major --timeout --json --allow-connect --allow-notifications --allow-write --negative-control --select --active-scan' ;;
        observe) words='-h --help --address-file --private-output --service-uuid --characteristic-uuid --instance-id --max-records --timeout --json --allow-connect --allow-notifications --allow-observation' ;;
        review-observation) words='-h --help --private-input --json --issue-draft-url' ;;
        review-owner-evidence) words='-h --help --private-input --decision --evidence-reference --review-output --allow-review-decision --json' ;;
        derive-owner-evidence) words='-h --help --private-input --public-output --review-receipt --allow-public-evidence --json' ;;
        *) return ;;
    esac

    case "$command:$previous" in
        completion:completion)
            mapfile -t COMPREPLY < <(compgen -W "bash" -- "$current")
            return
            ;;
        *) ;;
    esac

    case "$command:$current" in
        input:--simulate-profile=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        input:--map=*)
            COMPREPLY=()
            return
            ;;
        discover:--timeout=*)
            COMPREPLY=()
            return
            ;;
        pair:--address-file=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        pair:--timeout=*)
            COMPREPLY=()
            return
            ;;
        status:--address-file=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        status:--simulate-profile=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        status:--address=*|status:--timeout=*)
            COMPREPLY=()
            return
            ;;
        capabilities:--address-file=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        capabilities:--simulate-profile=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        capabilities:--address=*|capabilities:--timeout=*)
            COMPREPLY=()
            return
            ;;
        heart-rate:--address-file=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        heart-rate:--simulate-profile=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        heart-rate:--address=*|heart-rate:--timeout=*)
            COMPREPLY=()
            return
            ;;
        time-sync:--address-file=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        time-sync:--address=*|time-sync:--timeout=*)
            COMPREPLY=()
            return
            ;;
        history:--output=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        verify-device-info:--address-file=*|verify-device-info:--private-output=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        verify-device-info:--model-family=*|verify-device-info:--firmware-major=*|verify-device-info:--timeout=*)
            COMPREPLY=()
            return
            ;;
        observe:--address-file=*|observe:--private-output=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        observe:--service-uuid=*|observe:--characteristic-uuid=*|observe:--instance-id=*|observe:--max-records=*|observe:--timeout=*)
            COMPREPLY=()
            return
            ;;
        review-observation:--private-input=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        review-owner-evidence:--private-input=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        review-owner-evidence:--decision=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            mapfile -t COMPREPLY < <(compgen -W "promote reject" -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        review-owner-evidence:--evidence-reference=*|review-owner-evidence:--review-output=*)
            COMPREPLY=()
            return
            ;;
        derive-owner-evidence:--private-input=*|derive-owner-evidence:--public-output=*)
            option_prefix="${current%%=*}="
            option_value="${current#*=}"
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$option_value")
            for index in "${!COMPREPLY[@]}"; do
                COMPREPLY[index]="$option_prefix${COMPREPLY[index]}"
            done
            return
            ;;
        derive-owner-evidence:--review-receipt=*)
            COMPREPLY=()
            return
            ;;
    esac

    case "$command:$previous" in
        input:--simulate-profile)
            mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$current")
            return
            ;;
        input:--map)
            COMPREPLY=()
            return
            ;;
        discover:--timeout)
            COMPREPLY=()
            return
            ;;
        pair:--address-file)
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$current")
            return
            ;;
        pair:--timeout)
            COMPREPLY=()
            return
            ;;
        status:--address-file)
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$current")
            return
            ;;
        status:--simulate-profile)
            mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$current")
            return
            ;;
        status:--address|status:--timeout)
            COMPREPLY=()
            return
            ;;
        capabilities:--address-file)
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$current")
            return
            ;;
        capabilities:--simulate-profile)
            mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$current")
            return
            ;;
        capabilities:--address|capabilities:--timeout)
            COMPREPLY=()
            return
            ;;
        heart-rate:--address-file)
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$current")
            return
            ;;
        heart-rate:--simulate-profile)
            mapfile -t COMPREPLY < <(compgen -W "basic hid" -- "$current")
            return
            ;;
        heart-rate:--address|heart-rate:--timeout)
            COMPREPLY=()
            return
            ;;
        time-sync:--address-file)
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$current")
            return
            ;;
        time-sync:--address|time-sync:--timeout)
            COMPREPLY=()
            return
            ;;
        history:--output)
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$current")
            return
            ;;
        verify-device-info:--address-file|verify-device-info:--private-output)
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$current")
            return
            ;;
        verify-device-info:--model-family|verify-device-info:--firmware-major|verify-device-info:--timeout)
            COMPREPLY=()
            return
            ;;
        observe:--address-file|observe:--private-output)
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$current")
            return
            ;;
        observe:--service-uuid|observe:--characteristic-uuid|observe:--instance-id|observe:--max-records|observe:--timeout)
            COMPREPLY=()
            return
            ;;
        review-observation:--private-input)
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$current")
            return
            ;;
        review-owner-evidence:--private-input)
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$current")
            return
            ;;
        review-owner-evidence:--decision)
            mapfile -t COMPREPLY < <(compgen -W "promote reject" -- "$current")
            return
            ;;
        review-owner-evidence:--evidence-reference|review-owner-evidence:--review-output)
            COMPREPLY=()
            return
            ;;
        derive-owner-evidence:--private-input|derive-owner-evidence:--public-output)
            compopt -o filenames 2>/dev/null || true
            mapfile -t COMPREPLY < <(compgen -f -- "$current")
            return
            ;;
        derive-owner-evidence:--review-receipt)
            COMPREPLY=()
            return
            ;;
    esac
    mapfile -t COMPREPLY < <(compgen -W "$words" -- "$current")
}
complete -F _jring_completion jring
